#!/bin/bash

# A simple script that compile my Cpp & Py files
# Invoke through .vimrc


file=$(readlink -f "$1")
out="${file%.*}"

case "$file" in 
    *\.cpp) g++ "$1" -o "${out}"  && "${out}" ;;
    *\.py) python3 "$file" ;;
esac
