#!/bin/bash

if [[ -f ~/output.mkv ]]
    then
        n=1
        while [[ -f ~/output.mkv ]]
        do
            n=$((n+1))
        done
        filename="$HOME/output_$n.mkv"
    else
        filename="$HOME/output.mkv"
fi

ffmpeg -y \
-f x11grab \
-s 1366x768 \
-i :0.0 \
-f alsa -i default \
-c:v libx264 -r 30 -c:a flac $filename
